endroid_data_sanitize:
    entities:
        project:
            class: Endroid\Bundle\DataSanitizeBundle\Entity\Project
            list: [ 'id', 'name' ]
            edit: [ 'name' ]
        user:
            class: Endroid\Bundle\DataSanitizeBundle\Entity\User
            list: [ 'id', 'name' ]
            edit: [ 'name' ]
        task:
            class: Endroid\Bundle\DataSanitizeBundle\Entity\Task
            list: [ 'id', 'name', 'project', 'user', 'tags' ]
            edit: [ 'name', 'project', 'user', 'tags' ]
        tag:
            class: Endroid\Bundle\DataSanitizeBundle\Entity\Tag
            list: [ 'id', 'name' ]
            edit: [ 'name' ]